"""Add plot

Revision ID: 7a4d652f2e3f
Revises: 634aa24fac24
Create Date: 2020-09-16 00:10:54.813477

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '7a4d652f2e3f'
down_revision = '634aa24fac24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plots',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.Column('cw', sa.String(length=512), nullable=True),
                    sa.Column('local_only', sa.Boolean(), nullable=True),
                    sa.Column('uri', sa.String(length=512), nullable=True),
                    sa.Column('url', sa.String(length=512), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plots')
    # ### end Alembic commands ###
