"""empty message

Revision ID: 852101b6c46f
Revises: d545b4687420
Create Date: 2020-10-14 14:15:34.217769

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '852101b6c46f'
down_revision = 'd545b4687420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
