"""Add column

Revision ID: d545b4687420
Revises: 03c9d3e2aa7e
Create Date: 2020-09-30 13:36:05.858816

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd545b4687420'
down_revision = '03c9d3e2aa7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots',
                  sa.Column('created_by_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.create_foreign_key(None, 'plots', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plots', type_='foreignkey')
    op.drop_column('plots', 'created_by_id')
    # ### end Alembic commands ###
